"""Use actual jump/fire inputs and mirror draws to audit world/body camera tracking."""
import argparse,json,pathlib
from playwright.sync_api import sync_playwright
ap=argparse.ArgumentParser();ap.add_argument('base');ap.add_argument('output',type=pathlib.Path);ap.add_argument('--baseline',action='store_true');a=ap.parse_args();a.output.mkdir(parents=True,exist_ok=True)
with sync_playwright()as pw:
 b=pw.chromium.launch(channel='chrome',headless=True,args=['--ignore-gpu-blocklist','--enable-gpu','--use-angle=metal','--mute-audio']);p=b.new_page(viewport={'width':1280,'height':720});errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
 p.goto(a.base.rstrip('/')+'/?auto=training&manual=1&acc=yqcy&view=fp');p.wait_for_function('window.__glory?.game?.player&&!window.__glory._loadingMode&&!window.__glory.game.inputFrozen',timeout=90000);p.wait_for_load_state('networkidle')
 p.evaluate('''async()=>{const g=__glory.game,f=g.player,{input}=await import('./src/engine/input.js');g.settings.shake=false;g.settings.bob=false;g.aiFrozen=true;g.cinematic=null;window.cameraProof={};window.resetProof=()=>{g.camHook=null;input.clear();g.combat.clear();g.vfx.clear();f.resetState();f.pos.set(0,0,0);f.yaw=f.pitch=g.viewYaw=g.viewPitch=0;g.shakeAmt=g.camDip=0;g.inputFrozen=false;for(let i=0;i<60;i++){f.updateModel(1/60);g.updateCamera(1/60)}};window.runProof=frames=>{resetProof();const samples=[];input._press(input.binds.jump);for(let i=0;i<frames;i++){if(i===3)input._press(input.binds.attack);g.tick(1/60);g.updateCamera(1/60);samples.push({frame:i+1,feet:f.pos.y,eye:f.eyePos().y,cam:g.camera.position.y,lag:f.eyePos().y-g.camera.position.y,state:f.state,action:f.action?.stage});}const pos=g.camera.position.clone(),q=g.camera.quaternion.clone();g.camHook=cam=>{cam.position.copy(pos);cam.quaternion.copy(q)};g.render();return samples;};}''')
 samples=p.evaluate('runProof(60)');assert max(x['feet']for x in samples)>.8,samples;assert any(x['action']=='active'for x in samples),samples
 p.evaluate('runProof(9)');p.screenshot(path=str(a.output/'continuous-jump-shoot.png'))
 teleport=p.evaluate('''()=>{resetProof();const g=__glory.game,f=g.player;f.pos.y=2;f.onGround=false;f.state='jump';f.updateModel(1/60);g.updateCamera(1/60);return{feet:f.pos.y,eye:f.eyePos().y,cam:g.camera.position.y,lag:f.eyePos().y-g.camera.position.y}}''')
 mirror=p.evaluate('''()=>{resetProof();const g=__glory.game,f=g.player,m=g.scene.getObjectByName('mirror');f.pos.set(m.position.x+2,0,m.position.z);f.yaw=g.viewYaw=-Math.PI/2;f.pitch=g.viewPitch=-.12;f.startAction(f.chain[0],'atk',{chainIdx:0});f.action.stage='active';f.action.t=50;for(let i=0;i<60;i++){f.updateModel(1/60);g.updateCamera(1/60)}const draws=[];for(const mesh of f.rig.armParts.filter(m=>m.isSkinnedMesh)){const prev=mesh.onBeforeRender;mesh.onBeforeRender=function(r,s,c,...rest){prev.call(this,r,s,c,...rest);draws.push({id:this.uuid,camera:c===g.camera?'main':c===g.vmCamera?'overlay':'mirror',geo:this.geometry.uuid,index:this.geometry.index.count,world:this.matrixWorld.toArray(),bones:Array.from(this.skeleton.boneMatrices)})}}g.render();const shared=draws.filter(d=>d.camera==='main').every(d=>draws.some(m=>m.camera==='mirror'&&m.id===d.id&&['geo','index','world','bones'].every(k=>JSON.stringify(d[k])===JSON.stringify(m[k]))));const pos=g.camera.position.clone(),q=g.camera.quaternion.clone();g.camHook=cam=>{cam.position.copy(pos);cam.quaternion.copy(q)};return{shared,main:draws.filter(d=>d.camera==='main').length,mirror:draws.filter(d=>d.camera==='mirror').length,overlay:draws.filter(d=>d.camera==='overlay').length};}''')
 p.screenshot(path=str(a.output/'mirror-shared-gun-pose.png'))
 assert mirror['shared']and mirror['main']and mirror['mirror']and not mirror['overlay'],mirror
 report=dict(samples=samples,maxLag=max(x['lag']for x in samples),teleport=teleport,mirror=mirror,errors=errors)
 if not a.baseline:assert report['maxLag']<.12 and abs(teleport['lag'])<.05,report
 (a.output/'results.json').write_text(json.dumps(report,ensure_ascii=False,indent=2));print(json.dumps({k:v for k,v in report.items()if k!='samples'}));b.close();assert not errors,errors
